#!/bin/bash
# No arguments: `git status`
# With arguments: acts like git
# https://github.com/colbycheeze/dotfiles/blob/master/zsh/functions/g

g() {
    if [ $# -gt 0 ]; then
        git $@
    else
        git status
    fi
}

# Complete g like git
eval $(complete -p git 2>/dev/null | sed 's/ git$/ g/g' 2>/dev/null)
